### ISSUE TITLE
The problem of running the experiment

### ISSUE THREAD

**Issue by KyraGavin** [luckeciano/transformers-metarl#4]
Hello,Thank you very much for your code sharing. 
I couldn't find the running file transformer_ppo_halfcheetah.py while I was running.
Looking forward to your reply! Thank you!

**Comment by luckeciano** [comment]
Hi @MrCheny007,

You can find the script here:

https://github.com/luckeciano/transformers-metarl/blob/trmrl-torch/examples/torch/transformer_ppo_halfcheetah.py

I will also update the README to make sure the filepath is clear. Thanks for bringing this up.

**Comment by KyraGavin** [comment]
Thank you very much for your answer！
